name: ai_doorbell
description: An AI-powered doorbell system with face recognition capabilities
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.5
  camera: ^0.11.1
  path_provider: ^2.0.15
  permission_handler: ^12.0.0+1
  http: ^1.1.0
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  intl: ^0.19.0
  path: ^1.8.3
  image: ^4.0.17
  flutter_secure_storage: ^10.0.0-beta.4
  url_launcher: ^6.1.12
  google_ml_kit: ^0.16.3
  flutter_countdown_timer: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"